export const words = [
  {
    imagePath: '/images/words/bat.png',
    name: 'bat',
  }, {
    imagePath: '/images/words/bed.png',
    name: 'bed',
  }, {
    imagePath: '/images/words/bee.png',
    name: 'bee',
  }, {
    imagePath: '/images/words/car.png',
    name: 'car',
  }, {
    imagePath: '/images/words/cat.png',
    name: 'cat',
  }, {
    imagePath: '/images/words/dog.png',
    name: 'dog',
  }, {
    imagePath: '/images/words/ear.png',
    name: 'ear',
  }, {
    imagePath: '/images/words/fan.png',
    name: 'fan',
  }, {
    imagePath: '/images/words/fire.png',
    name: 'fire',
  }, {
    imagePath: '/images/words/frog.png',
    name: 'frog',
  }, {
    imagePath: '/images/words/ham.png',
    name: 'ham',
  }, {
    imagePath: '/images/words/jam.png',
    name: 'jam',
  }, {
    imagePath: '/images/words/log.png',
    name: 'log',
  }, {
    imagePath: '/images/words/man.png',
    name: 'man',
  }, {
    imagePath: '/images/words/nose.png',
    name: 'nose',
  }, {
    imagePath: '/images/words/pan.png',
    name: 'pan',
  }, {
    imagePath: '/images/words/shoe.png',
    name: 'shoe',
  }, {
    imagePath: '/images/words/apple.png',
    name: 'apple',
  }, {
    imagePath: '/images/words/banana.png',
    name: 'banana',
  }, {
    imagePath: '/images/words/bike.png',
    name: 'bike',
  }, {
    imagePath: '/images/words/bread.png',
    name: 'bread',
  }, {
    imagePath: '/images/words/egg.png',
    name: 'egg',
  }, {
    imagePath: '/images/words/flour.png',
    name: 'flour',
  }, {
    imagePath: '/images/words/fork.png',
    name: 'fork',
  }, {
    imagePath: '/images/words/house.png',
    name: 'house',
  }, {
    imagePath: '/images/words/peas.png',
    name: 'peas',
  }, {
    imagePath: '/images/words/pepper.png',
    name: 'pepper',
  }, {
    imagePath: '/images/words/pool.png',
    name: 'pool',
  }, {
    imagePath: '/images/words/potato.png',
    name: 'potato',
  }, {
    imagePath: '/images/words/salt.png',
    name: 'salt',
  },
];
